export const animals = [
    {
        animal:"Bear",
        image:"/animals/bear.png",
    },
    {
        animal:"Fox",
        image:"/animals/fox.png",
    },
    {
        animal:"mangoose",
        image:"/animals/mangoose.png",
    },
    {
        animal:"otter",
        image:"/animals/otter.png",
    },
    {
        animal:"owl",
        image:"/animals/owl.png",
    },
    {
        animal:"porc",
        image:"/animals/porc.png",
    },
    {
        animal:"rabbit",
        image:"/animals/rabbit.png",
    },
    {
        animal:"raccoon",
        image:"/animals/raccoon.png",
    },
    {
        animal:"rat",
        image:"/animals/rat.png",
    },
    {
        animal:"skunk",
        image:"/animals/skunk.png",
    },
    {
        animal:"squirrel",
        image:"/animals/squirrel.png",
    },
    {
        animal:"bat",
        image:"/animals/bat.png",
    },
    {
        animal:"dear",
        image:"/animals/dear.png",
    },
    {
        animal:"frog",
        image:"/animals/frog.png",
    },
    {
        animal:"hamster",
        image:"/animals/hamster.png",
    },

]